### ISSUE TITLE
The play button is missing

### ISSUE THREAD

**Issue by sadqiang** [J0Nreynolds/AndroidOpenCVCamera#1]
I already followed the instruction but Android Studio does not show the play or run button as follows.

![43670862-34474606-97bb-11e8-86f1-19c3595b486d](https://user-images.githubusercontent.com/22278424/43672836-69ea0d28-97e0-11e8-805e-419b99faa156.png)

I used Windows 10,  Android Studio, and OpenCV Android SDK with the latest version.

**Comment by J0Nreynolds** [comment]
Hi @sadqiang, I'd like to try to help you with this problem, but I'm not an expert with Android Studio. However, I do see your editor has a message informing you to sync your project. Have you tried that?

**Comment by sadqiang** [comment]
Yes. I have tried it. Nothing changes.

**Comment by J0Nreynolds** [comment]
Have you tried googling the issue or anything? I feel like this issue is something that people may run into for projects other than this one. Perhaps take a look at [this](https://stackoverflow.com/questions/28385172/run-button-is-disabled-in-android-studio).

**Comment by J0Nreynolds** [comment]
@sadqiang, I've managed the reproduce the problem on my Windows partition - I'll see if I can find a way to fix it.

**Comment by sadqiang** [comment]
I attempted to follow the accepted answer in your link but I have no module to select as the drop down has nothing.

![image](https://user-images.githubusercontent.com/22278424/43671918-60427fde-97cd-11e8-9656-297d53d3a049.png)

**Comment by J0Nreynolds** [comment]
Hi @sadqiang. Please pull the new version of the repo. I apologize as one of my recent commits accidentally removed the settings.gradle file, which is why the app module is missing.

**Comment by J0Nreynolds** [comment]
One last thing, for Windows, make sure you are careful with the format of strings you use in CMakeLists.txt. You need to use forward slashes between directories, and backslashes should only be used to escape whitespace characters. Example:

> C:\Users\Jonathan Reynolds\Documents\GitHub\AndroidOpenCVCamera

becomes `set(pathToProject C:/Users/Jonathan\ Reynolds/Documents/GitHub/AndroidOpenCVCamera)`

**Comment by sadqiang** [comment]
Thank you. I am still installing Android NDK so I will report the result in a couple of minutes.

**Comment by sadqiang** [comment]
Could you let me know, what are all the tools needed to build this project? I have no Git.exe installed. I have Android NDK copied to the c:\ but I have not configured the PATH yet.

![image](https://user-images.githubusercontent.com/22278424/43672215-ac714cfe-97d3-11e8-892a-ef21962c8b63.png)

**Comment by J0Nreynolds** [comment]
For me, I just had to install Android NDK and CMake. When I built and ran on Windows a short bit ago, Android Studio gave me the option to install them easily from the Event Log. Open the Event Log view in the bottom right and see if you have the same options after you sync or build.

I believe you should also be able to do this by yourself through the SDK manager. Just click Tools -> SDK Manager. Then, click SDK Tools. You can see an example with NDK and CMake installed below:

<img width="1396" alt="screen shot 2018-08-03 at 9 48 51 pm" src="https://user-images.githubusercontent.com/5325576/43672637-2dbd9ee2-9767-11e8-88b5-5571abd7cc09.png"> I would keep trying to sync/build until success, then try running the application. 

You may want to start clean by re-cloning the repo - it's possible you've accidentally misconfigured the project, as it was not this difficult for me on Windows.

Also, in general, the git and other VCS settings shouldn't matter.
