### ISSUE TITLE
How to turn on camera preview portrait mode

### ISSUE THREAD

**Issue by AnhQuanTran** [J0Nreynolds/AndroidOpenCVCamera#2]
Hello. Thanks for your project demo.
How to turn on camera preview portrait mode
Preview mode default is LANDSCAPE. 

![image](https://user-images.githubusercontent.com/21956433/44546505-575a0e80-a742-11e8-96ec-554285718e6a.png)

But error occured when i comment this line 
` setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);`
Or change to 
` setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);`

 I need to do use portrait mode like this

![image](https://user-images.githubusercontent.com/21956433/44546636-bd469600-a742-11e8-937a-6cb2287f9cb4.png)

 Thanks

**Comment by J0Nreynolds** [comment]
As far as I know, this is not possible at the moment. It seems there is a bug in the OpenCV Android SDK that prevents users from properly using portrait mode.
