### ISSUE TITLE
FPS is slow when processing image in NDK

### ISSUE THREAD

**Issue by AnhQuanTran** [J0Nreynolds/AndroidOpenCVCamera#4]
With preview mode, no processing. FPS up to 26~29. But when i run this function 
![image](https://user-images.githubusercontent.com/21956433/44618475-c6e61000-a8a0-11e8-9129-f75885f4a686.png)
FPS down to 16
How to fix it?
Thanks

**Comment by J0Nreynolds** [comment]
Why do you think that this is an issue that can be fixed? Do you expect to be able to process images instantaneously? 

If you have 30 FPS without modifying the input images, then surely, applying some processing to each frame will take up time between each frame draw call, and the FPS must get lower. I don't think you have a clear understanding of how this works.

In general, if you'd like to make your FPS higher, you should decrease the time it takes to process each image.

**Comment by AnhQuanTran** [comment]
That is an issue can be fixed. I did it. FPS up to 20-28 instead 16

**Comment by J0Nreynolds** [comment]
I think you misunderstood my comment. If you aren't going to ask questions that are pertinent to this project and the code in it, then please refrain from making issues. As I suggested earlier, the FPS has nothing to do with any of the code I wrote, and it's up to you to write performant frame processing code.

**Comment by AnhQuanTran** [comment]
Sorry. I misunderstood. ;)
